version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
  django:
    image: registry.gitlab.propulsion-home.ch/full-stack/batch-05-2019/group-projects/aries:backend
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./app:/app/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    image: registry.gitlab.propulsion-home.ch/full-stack/batch-05-2019/group-projects/aries:frontend
    command: ["npm", "start"]
    volumes:
      - ./frontend:/app/frontend
      - node-modules:/app/frontend/node_modules
    ports:
      - "3000:3000"

volumes:
  node-modules:
