# Generated by Django 2.0.3 on 2018-03-30 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import project.api.helpers


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0004_userprofile_registration_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=100, verbose_name='status')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests', to=settings.AUTH_USER_MODEL, verbose_name='receiver')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to=settings.AUTH_USER_MODEL, verbose_name='requester')),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='registration_code',
        ),
        migrations.AddField(
            model_name='post',
            name='shared',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.Post', verbose_name='shared'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='code',
            field=models.CharField(default=project.api.helpers.code_generator, help_text='random code used for registration and for password reset', max_length=15, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='followees',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='following'),
        ),
    ]
