import { SAVE_RESTAURANTS } from "../types";


const initial = {
    "1": {
        id: 1,
        name: "restaurant name",
        category: "category",
        country: "country",
        street: "street",
        city: "city",
        zip: "zip",
        website: "website.com",
        phone: "12345678",
        email: "email@example.com",
        opening_hours: "Monday-Friday, 09:00-20:00",
        price_level: 3,
        restaurant_pic: "restaurant pic as base64 or url??",
        "ratings_avg": 4.5,
        "ratings_count": 13
    },
    "2": {
        id: 2,
        name: "restaurant name",
        category: "category",
        country: "country",
        street: "street",
        city: "city",
        zip: "zip",
        website: "website.com",
        phone: "12345678",
        email: "email@example.com",
        opening_hours: "Monday-Friday, 09:00-20:00",
        price_level: 3,
        restaurant_pic: "restaurant pic as base64 or url??",
        "ratings_avg": 4.5,
        "ratings_count": 3
    },
    "3": {
        id: 3,
        name: "restaurant name",
        category: "category",
        country: "country",
        street: "street",
        city: "city",
        zip: "zip",
        website: "website.com",
        phone: "12345678",
        email: "email@example.com",
        opening_hours: "Monday-Friday, 09:00-20:00",
        price_level: 3,
        restaurant_pic: "restaurant pic as base64 or url??",
        "ratings_avg": 4.0,
        "ratings_count": 2
    },
    "4": {
        id: 4,
        name: "restaurant name",
        category: "category",
        country: "country",
        street: "street",
        city: "city",
        zip: "zip",
        website: "website.com",
        phone: "12345678",
        email: "email@example.com",
        opening_hours: "Monday-Friday, 09:00-20:00",
        price_level: 3,
        restaurant_pic: "restaurant pic as base64 or url??",
        "ratings_avg": 3.5,
        "ratings_count": 42
    },
    "5": {
        id: 5,
        name: "restaurant name",
        category: "category",
        country: "country",
        street: "street",
        city: "city",
        zip: "zip",
        website: "website.com",
        phone: "12345678",
        email: "email@example.com",
        opening_hours: "Monday-Friday, 09:00-20:00",
        price_level: 3,
        restaurant_pic: "restaurant pic as base64 or url??",
        "ratings_avg": 4.5,
        "ratings_count": 13
    },
    "6": {
        id: 6,
        name: "restaurant name",
        category: "category",
        country: "country",
        street: "street",
        city: "city",
        zip: "zip",
        website: "website.com",
        phone: "12345678",
        email: "email@example.com",
        opening_hours: "Monday-Friday, 09:00-20:00",
        price_level: 3,
        restaurant_pic: "restaurant pic as base64 or url??",
        "ratings_avg": 4.5,
        "ratings_count": 3
    },
    "7": {
        id: 7,
        name: "restaurant name",
        category: "category",
        country: "country",
        street: "street",
        city: "city",
        zip: "zip",
        website: "website.com",
        phone: "12345678",
        email: "email@example.com",
        opening_hours: "Monday-Friday, 09:00-20:00",
        price_level: 3,
        restaurant_pic: "restaurant pic as base64 or url??",
        "ratings_avg": 4.0,
        "ratings_count": 2
    },
    "8": {
        id: 8,
        name: "restaurant name",
        category: "category",
        country: "country",
        street: "street",
        city: "city",
        zip: "zip",
        website: "website.com",
        phone: "12345678",
        email: "email@example.com",
        opening_hours: "Monday-Friday, 09:00-20:00",
        price_level: 3,
        restaurant_pic: "restaurant pic as base64 or url??",
        "ratings_avg": 3.5,
        "ratings_count": 42
    },
    "9": {
        id: 9,
        name: "restaurant name",
        category: "category",
        country: "country",
        street: "street",
        city: "city",
        zip: "zip",
        website: "website.com",
        phone: "12345678",
        email: "email@example.com",
        opening_hours: "Monday-Friday, 09:00-20:00",
        price_level: 3,
        restaurant_pic: "restaurant pic as base64 or url??",
        "ratings_avg": 4.5,
        "ratings_count": 13
    },
    "10": {
        id: 10,
        name: "restaurant name",
        category: "category",
        country: "country",
        street: "street",
        city: "city",
        zip: "zip",
        website: "website.com",
        phone: "12345678",
        email: "email@example.com",
        opening_hours: "Monday-Friday, 09:00-20:00",
        price_level: 3,
        restaurant_pic: "restaurant pic as base64 or url??",
        "ratings_avg": 4.5,
        "ratings_count": 3
    },
    "11": {
        id: 11,
        name: "restaurant name",
        category: "category",
        country: "country",
        street: "street",
        city: "city",
        zip: "zip",
        website: "website.com",
        phone: "12345678",
        email: "email@example.com",
        opening_hours: "Monday-Friday, 09:00-20:00",
        price_level: 3,
        restaurant_pic: "restaurant pic as base64 or url??",
        "ratings_avg": 4.0,
        "ratings_count": 2
    },
    "12": {
        id: 12,
        name: "restaurant name",
        category: "category",
        country: "country",
        street: "street",
        city: "city",
        zip: "zip",
        website: "website.com",
        phone: "12345678",
        email: "email@example.com",
        opening_hours: "Monday-Friday, 09:00-20:00",
        price_level: 3,
        restaurant_pic: "restaurant pic as base64 or url??",
        "ratings_avg": 3.5,
        "ratings_count": 42
    },

};

export const restaurantReducer = (restaurants=initial, action) => {
    switch(action.type) {
        case SAVE_RESTAURANTS:
            const temp = {...restaurants, ...action.payload.restaurants};
            return temp;
        default:
            return restaurants;
    }
};

